name: VeiledCitizen
description: "VeiledCitizen er en anonym side for frigivelsen af skjulte information angående kirker i Danmark."
meta_description: "VeiledCitizen er en anonym side for frigivelsen af skjulte information angående kirker i Danmark."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://veiledcitizen.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://veiledcitizen.github.io'
author:         'FirstCitizen'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
